FROM node:18

WORKDIR /app

COPY package*.json ./

ENV NODE_ENV=development

RUN npm install --include=dev

COPY . .

# Ensure node_modules/.bin is on PATH
ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 3000

# Env Variables to ensure that webhooks work correclty with auto refresh in dev mode
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true
ENV WDS_SOCKET_PORT=3000

CMD ["npm", "start"]