version: "3.8"

services:
  reverse-proxy:
    environment:
      - FRONTEND_PORT=80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
