version: '3.8'

services:
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ./reverseProxy
    environment:
      - FRONTEND_PORT=3000  # Frontend will run on port 3000 as a live reload react dev server
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    volumes:
      - ./backend:/app

  database:
    container_name: database
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: