version: '3.8'

services:
  reverse-proxy:
    volumes: 
      - ./reverseProxy/default.dev.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - FRONTEND_PORT=3000  # Frontend will run on port 3000 as a live reload react dev server

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0  # Prevent Webpack
      - NODE_ENV=development