services:
  reverse-proxy:
    volumes:
      - ./reverseProxy/default.prod.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - FRONTEND_INTERNAL_PORT=${FRONTEND_INTERNAL_PORT_PROD} # Frontend will run on port 80 in production mode

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - PORT=${FRONTEND_INTERNAL_PORT_DEV}
      - NODE_ENV=production
