version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - PORT=8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"