version: '3.8'

services:
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ./reverseProxy
    environment:
      - FRONTEND_PORT=3000  # Frontend will run on port 3000 as a live reload react dev server
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      - PORT=8000
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
