version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - PORT=8000
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # for mapping webpack dev server to 80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0  # Prevent Webpack

  nginx:
    build:
      context: ./reverseProxy
    container_name: reverseProxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend