FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ /app/app/

COPY entrypoint.sh /app/entrypoint.sh
COPY wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/entrypoint.sh /app/wait-for-it.sh

EXPOSE ${PORT}

# CMD uvicorn app.main:app --host 0.0.0.0 --port ${PORT}
ENTRYPOINT ["/entrypoint.sh"]