"""Initial Migration

Revision ID: 3ea80718e356
Revises: 
Create Date: 2025-03-10 18:35:49.607732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea80718e356'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_search_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_search_api_keys_api_key'), 'youtube_search_api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_youtube_search_api_keys_date_created'), 'youtube_search_api_keys', ['date_created'], unique=False)
    op.create_index(op.f('ix_youtube_search_api_keys_id'), 'youtube_search_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_search_api_keys_is_active'), 'youtube_search_api_keys', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_search_api_keys_is_active'), table_name='youtube_search_api_keys')
    op.drop_index(op.f('ix_youtube_search_api_keys_id'), table_name='youtube_search_api_keys')
    op.drop_index(op.f('ix_youtube_search_api_keys_date_created'), table_name='youtube_search_api_keys')
    op.drop_index(op.f('ix_youtube_search_api_keys_api_key'), table_name='youtube_search_api_keys')
    op.drop_table('youtube_search_api_keys')
    # ### end Alembic commands ###
