"""Updated models

Revision ID: 5c295d69b698
Revises: c014edb00c21
Create Date: 2025-03-09 19:30:01.347690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c295d69b698'
down_revision: Union[str, None] = 'c014edb00c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_api_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_configs_id'), 'app_configs', ['id'], unique=False)
    op.create_index(op.f('ix_app_configs_youtube_api_key'), 'app_configs', ['youtube_api_key'], unique=True)
    op.drop_index('ix_youtube_api_keys_api_key', table_name='youtube_api_keys')
    op.drop_index('ix_youtube_api_keys_id', table_name='youtube_api_keys')
    op.drop_table('youtube_api_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='youtube_api_keys_pkey')
    )
    op.create_index('ix_youtube_api_keys_id', 'youtube_api_keys', ['id'], unique=False)
    op.create_index('ix_youtube_api_keys_api_key', 'youtube_api_keys', ['api_key'], unique=True)
    op.drop_index(op.f('ix_app_configs_youtube_api_key'), table_name='app_configs')
    op.drop_index(op.f('ix_app_configs_id'), table_name='app_configs')
    op.drop_table('app_configs')
    # ### end Alembic commands ###
