"""create api_keys table

Revision ID: c014edb00c21
Revises: 
Create Date: 2025-03-08 23:43:29.602880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c014edb00c21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_api_keys_api_key'), 'youtube_api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_youtube_api_keys_id'), 'youtube_api_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_api_keys_id'), table_name='youtube_api_keys')
    op.drop_index(op.f('ix_youtube_api_keys_api_key'), table_name='youtube_api_keys')
    op.drop_table('youtube_api_keys')
    # ### end Alembic commands ###
